// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TokenBurn.Processor.Persistence;

#nullable disable

namespace TokenBurn.Processor.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    [Migration("20260804195057_AddImportCommands")]
    partial class AddImportCommands
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("telemetry")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TokenBurn.Processor.Domain.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("")
                        .HasColumnName("agent_id");

                    b.Property<long?>("CacheReadTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cache_read_tokens");

                    b.Property<long?>("CacheWriteTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cache_write_tokens");

                    b.Property<decimal?>("CostUsd")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_id");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<string>("ModelSlug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model_slug");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<Guid?>("ParentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_run_id");

                    b.Property<string>("Persona")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("persona");

                    b.Property<decimal?>("PriceMultiplier")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("price_multiplier");

                    b.Property<string>("PricingStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pricing_status");

                    b.Property<decimal?>("ReportedCostUsd")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("reported_cost_usd");

                    b.Property<string>("Service")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("service");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("session_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("Workspace")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("workspace");

                    b.HasKey("Id");

                    b.HasIndex("ModelSlug", "StartedAt");

                    b.HasIndex("Persona", "StartedAt");

                    b.HasIndex("SessionId", "AgentId")
                        .IsUnique();

                    b.HasIndex("StartedAt", "Id")
                        .IsDescending(true, false);

                    b.ToTable("agent_runs", "telemetry", t =>
                        {
                            t.HasCheckConstraint("ck_agent_runs_parent_not_self", "parent_run_id <> id");

                            t.HasCheckConstraint("ck_agent_runs_pricing_status", "pricing_status IN ('Priced','Quarantined','Unpriceable')");

                            t.HasCheckConstraint("ck_agent_runs_status", "status IN ('Running','Completed','Failed','Cancelled','Unknown')");
                        });
                });

            modelBuilder.Entity("TokenBurn.Processor.Domain.ImportCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset?>("CooldownUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cooldown_until");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("HandlingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("handling_started_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CooldownUntil");

                    b.HasIndex("Type", "Payload")
                        .IsUnique()
                        .HasFilter("status IN ('Queued','Running')");

                    b.ToTable("import_commands", "telemetry", t =>
                        {
                            t.HasCheckConstraint("ck_import_commands_status", "status IN ('Queued','Running','Completed','Failed')");
                        });
                });

            modelBuilder.Entity("TokenBurn.Processor.Persistence.ModelAlias", b =>
                {
                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alias");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("service");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.HasKey("Alias");

                    b.ToTable("model_aliases", "telemetry");
                });

            modelBuilder.Entity("TokenBurn.Processor.Persistence.ModelPrice", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<string>("Service")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("service");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<decimal>("CacheReadPerMtok")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("cache_read_per_mtok");

                    b.Property<decimal>("CacheWritePerMtok")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("cache_write_per_mtok");

                    b.Property<int?>("ContextWindow")
                        .HasColumnType("integer")
                        .HasColumnName("context_window");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<decimal>("InputPerMtok")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("input_per_mtok");

                    b.Property<decimal>("OutputPerMtok")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("output_per_mtok");

                    b.HasKey("Slug", "Service", "EffectiveFrom");

                    b.HasIndex("Slug", "Service", "EffectiveFrom")
                        .IsDescending(false, false, true);

                    b.ToTable("model_prices", "telemetry");
                });
#pragma warning restore 612, 618
        }
    }
}
