// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TokenBurn.Processor.Persistence;

#nullable disable

namespace TokenBurn.Processor.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    [Migration("20260803174505_InitialTelemetry")]
    partial class InitialTelemetry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("telemetry")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TokenBurn.Processor.Domain.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("")
                        .HasColumnName("agent_id");

                    b.Property<long?>("CacheReadTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cache_read_tokens");

                    b.Property<long?>("CacheWriteTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cache_write_tokens");

                    b.Property<decimal?>("CostUsd")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_id");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<string>("ModelSlug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model_slug");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<Guid?>("ParentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_run_id");

                    b.Property<string>("Persona")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("persona");

                    b.Property<decimal?>("PriceMultiplier")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("price_multiplier");

                    b.Property<string>("PricingStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pricing_status");

                    b.Property<decimal?>("ReportedCostUsd")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("reported_cost_usd");

                    b.Property<string>("Service")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("service");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("session_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("Workspace")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("workspace");

                    b.HasKey("Id");

                    b.HasIndex("ModelSlug", "StartedAt");

                    b.HasIndex("Persona", "StartedAt");

                    b.HasIndex("SessionId", "AgentId")
                        .IsUnique();

                    b.HasIndex("StartedAt", "Id")
                        .IsDescending(true, false);

                    b.ToTable("agent_runs", "telemetry", t =>
                        {
                            t.HasCheckConstraint("ck_agent_runs_parent_not_self", "parent_run_id <> id");

                            t.HasCheckConstraint("ck_agent_runs_pricing_status", "pricing_status IN ('Priced','Quarantined','Unpriceable')");

                            t.HasCheckConstraint("ck_agent_runs_status", "status IN ('Running','Completed','Failed','Cancelled','Unknown')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
