<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><OutputType>Exe</OutputType><AssemblyName>api.TokenBurn.Insights</AssemblyName><RootNamespace>Api.TokenBurn.Insights</RootNamespace></PropertyGroup>
  <ItemGroup><ProjectReference Include="../TokenBurn.Common/TokenBurn.Common.csproj" />
    <ProjectReference Include="../TokenBurn.Contracts/TokenBurn.Contracts.csproj" /></ItemGroup>
</Project>
